version: '3.1'

services: 
    demophon-api:
      image: demophon-api
      build: '../api'
      restart: on-failure
      ports:
        - "3001:3001"
    demophon-web:
      image: demophon-web
      build: '../web'
      restart: on-failure
      ports:
        - "3000:80"